name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node for frontend lint & test (optional)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: |
          cd frontend && npm ci

      - name: Run frontend tests (collect coverage)
        run: |
          cd frontend && npm test -- --coverage --watchAll=false

      # Set up PHP for backend tests
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_sqlite

      - name: Install composer deps
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHP tests (with coverage)
        run: |
          mkdir -p coverage-php
          vendor/bin/phpunit --coverage-clover coverage-php/coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >-
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}

